# 2.4 Try Catch
    unexpected events can occur so try-catch acts as a guard for your code
        "Look out something unexpected might happen"
### Goal:
    Deal with the error without crashing the program
    Examples:
        Read in a file that is not there
        Access value outside of an array
            Array out of bounds
            arr= int[4]
            int k = arr[7] :(
                this is security issue where use might gain access to private info
            try arr[7]
            catch (do something else)